name: lingu
description: "A language learning app."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  http_parser: ^4.1.2
  record: 6.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  just_audio: ^0.9.38     # audio playback (writes file then plays)
  http: ^1.2.2            # upload to Python API
  path_provider: ^2.1.4   # temp dir for files
  permission_handler: ^11.3.1


flutter:
  uses-material-design: true
